baseURL: '/'
pagination:
  pagerSize: 5
defaultContentLanguage: 'pt'
theme: "PaperMod"

params:
  subtitle: 'minha página pessoal'
  contact:
    email: 'joao.amadeu@unifio.edu.br'
  contentTypeName: "posts"
  showMenuItems: 2
  ShowFullTextinRSS: true
  showLanguageSelector: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  defaultTheme: dark 
  profileMode:
    enabled: true 
    imageUrl: "posts/images/eu.JPEG"
    imageWidth: 120
    imageHeight: 120

outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  defaultMarkdownHandler: 'goldmark'
  goldmark:
    duplicateResourceFiles: false
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: 'https'
      strikethrough: true
      table: true
      taskList: true
      cjk:
        eastAsianLineBreaks: false
        eastAsianLineBreaksStyle: 'simple'
        enable: false
        escapedSpace: false
      extras:
        delete:
          enable: false
        insert:
          enable: false
        mark:
          enable: false
        subscript:
          enable: false
        superscript:
          enable: false
      passthrough:
        enable: false
        delimiters:
          block: []
          inline: []
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      autoDefinitionTermID: false
      autoHeadingID: true
      autoIDType: 'github'
      wrapStandAloneImageWithinParagraph: true
      attribute:
        block: false
        title: true
    renderHooks:
      goldmark:
        renderHooks:
          image:
            enableDefault: false
          link:
            enableDefault: false
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

languages:
  pt:
    languageName: "Português"
    title: "fortmea"
    params:
      subtitle: "Minha página pessoal"
      copyright: "fortmea, 2025"
      profileMode:
        title: fortmea
        imageTitle: eu
        buttons:
          - name: Postagens
            url: posts
          - name: Tags
            url: tags
          - name: Pesquisar
            url: search
      socialIcons:
        - name: github
          title: Meu Github
          url: "https://github.com/fortmea"
        - name: LinkedIn
          title: Meu LinkedIn
          url: "https://www.linkedin.com/in/jo%C3%A3o-walter-amadeu"
    logo:
      logoText: "Fortmea"
      logoHomeLink: "/"
    menu:
      main:
        - identifier: "about"
          name: "Sobre"
          url: "/about"
  en:
    languageName: "English"
    title: "fortmea"
    params:
      subtitle: "My personal page"
      copyright: "fortmea, 2025"
      menuMore: "Show more"
      readMore: "Read more"
      readOtherPosts: "Other posts"
      profileMode:
        title: fortmea
        imageTitle: me
        buttons:
          - name: Posts
            url: posts
          - name: Tags
            url: tags
          - name: Search
            url: search
      socialIcons:
        - name: github
          title: My github profile
          url: "https://github.com/fortmea"
        - name: LinkedIn
          title: My linkedin profile
          url: "https://www.linkedin.com/in/jo%C3%A3o-walter-amadeu"
    logo:
      logoText: "Fortmea"
      logoHomeLink: "/"
    menu:
      main:
        - identifier: "about"
          name: "About"
          url: "/about"
