name: Translate posts from content folder
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  get-files:
    name: Get Markdown Files to Translate
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.get_files.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List Markdown files (excluindo *.en.md e aqueles que já possuem versão .en.md)
        id: get_files
        run: |
          files=$(find content -type f -name "*.md" ! -name "*.en.md" | while read file; do
            if [ ! -f "${file%.md}.en.md" ]; then
              echo "$file"
            fi
          done | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=files::$files"

  translate:
    name: Translate Each File
    needs: get-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.get-files.outputs.files) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read file content
        id: read_file
        run: |
          echo "Lendo o conteúdo do arquivo: ${{ matrix.file }}"
          content=$(cat "${{ matrix.file }}" | jq -Rs .)
          echo "::set-output name=content::$content"

      - name: Translate file content with DeepL
        id: deepl
        uses: fabasoad/translation-action@main
        with:
          provider: google
          lang: pt-en
          
          source: ${{ steps.read_file.outputs.content }}
          #api_key: ${{ secrets.DEEPL_API_KEY }}
      - name: Save translated file
        run: |
          original="${{ matrix.file }}"
          new_file="${original%.md}.en.md"
          echo "Salvando tradução em: $new_file"
          printf "%s" '${{ steps.deepl.outputs.text}}'> "$new_file"
          echo "\n"
          cd content
          ls
          cd posts
          ls

      - name: Upload translated file
        run: |
            original="${{ matrix.file }}"
            new_file="${original%.md}.en.md"
            artifact_name="translated-md-${original//\//_}"  # Substitui / por _ para evitar problemas no nome do artifact
        
            echo "Uploading $new_file as $artifact_name"
            mv "$new_file" "$artifact_name"  # Renomeia para evitar problemas com caminhos
            gh run upload-artifact --name "$artifact_name" --path "$artifact_name"


  commit:
    name: Commit Translated Files
    needs: translate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download translated files
        uses: actions/download-artifact@v4
        with:
          name: translated-md
          path: content/
      - name: Move translated files back to original locations
        run: |
            for artifact in translated-md-*; do
              if [ -d "$artifact" ]; then
                mv "$artifact"/* content/
              fi
            done

      - name: Commit and push translations
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b translation-update
          git add .
          git commit -m "Translated Markdown files" || echo "Nenhuma alteração para commit"
          git push origin translation-update || echo "Nada para enviar"