name: Translate posts from content folder
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  get-files:
    name: Get Markdown Files to Translate
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.get_files.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List Markdown files (excluindo *.en.md)
        id: get_files
        run: |
          files=$(find content -type f -name "*.md" ! -name "*.en.md" | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=files::$files"

  translate:
    name: Translate Each File
    needs: get-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.get-files.outputs.files) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read file content
        id: read_file
        run: |
          content=$(cat "${{ matrix.file }}")
          echo "::set-output name=content::$content"

      - name: Translate file content with DeepL
        id: deepl
        uses: fabasoad/translation-action@main
        with:
          provider: deepl
          lang: pt-en-US
          source: ${{ steps.read_file.outputs.content }}
          api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Save translated file
        run: |
          original="${{ matrix.file }}"
          new_file="${original%.md}.en.md"
          touch "$new_file" 
          echo "${{ steps.deepl.outputs.text }}"
          echo "${{ steps.deepl.outputs.text }}" > "$new_file"
          echo "Arquivo salvo: $new_file"
          cd content
          ls
          cd posts
          ls

  commit:
    name: Commit Translated Files
    needs: translate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and switch to new branch
        run: |
          git checkout -b translation-update

      - name: Check for changes
        run: git status

      - name: Commit and push translations
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Translated Markdown files" || echo "Nada para commitar"
          git push origin translation-update || echo "Nada para enviar"