name: Translate posts from content folder

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    paths:
      - 'content/*.md'
    branches:
      - main

jobs:
  deepl:
    name: DeepL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find Markdown files
        id: find_files
        run: |
          files=$(find content -name '*.md' | grep -vE '\.en\.md$')
          echo "files=$(echo $files | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV

      - name: Translate files and commit changes
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: |
          for file in $(echo ${{ env.files }} | jq -r '.[]'); do
            basename=$(basename "$file" .md)
            if [ -f "content/${basename}.en.md" ]; then
              echo "Skipping $file (manual translation exists)"
              continue
            fi
            translation=$(curl -s -X POST "https://api-free.deepl.com/v2/translate" \
              -H "Authorization: DeepL-Auth-Key $DEEPL_API_KEY" \
              -d "text=$(cat "$file")" -d "target_lang=en" | jq -r '.translations[0].text')
            echo "$translation" > "content/${basename}.en.md"
            git add "content/${basename}.en.md"
          done
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git commit -m "Add translated files"
            git push
          fi
